version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter
    ports:
        - 8888:8888
    volumes:
        - .:/home/jovyan/work
    environment:
        JUPYTER_ENABLE_LAB: "yes"